import { Project } from './projects';
export const Projects :Project[]=[
  {project_ID:1, project_Name:"first Project of you", weekly_Workload:"do whatever you want",
  // deadline:"12/10/2018",
  number_Of_Members:15,state:"done"},
  {project_ID:2, project_Name:"second Project you have to do", weekly_Workload:"implement the UI",
  // deadline:"2/5/2018",
  number_Of_Members:4,state:"ongoing"},
  {project_ID:3, project_Name:"this is the third project", weekly_Workload:"design the database",
  // deadline:"5/7/2018",
  number_Of_Members:8,state:"done"},
  {project_ID:4, project_Name:"the forth project you have to implement", weekly_Workload:"i want to see only one functionality",
   // deadline:"10/9/2018",
   number_Of_Members:20,state:"done"},
  {project_ID:5, project_Name:"this is the fifth project", weekly_Workload:"need to see your SRS and SDS",
  // deadline:"1/17/2018",
  number_Of_Members:14,state:"ongoing"},
  {project_ID:6, project_Name:"sixth project is more advanced project", weekly_Workload:"do whatever you want",
   // deadline:"9/25/2018",
    number_Of_Members:9,state:"ongoing"},
  {project_ID:7, project_Name:"eighth project is a bit easy project ", weekly_Workload:"you are free to implement this at this week",
  // deadline:"8/29/2018",
  number_Of_Members:4,state:"done"},
  {project_ID:8, project_Name:"this is the last project", weekly_Workload:"find the technologies you have to use in this project",
  // deadline:"7/11/2018",
  number_Of_Members:7,state:"ongoing"},
];
